name: 'Push to another repo'

runs:
  using: composite
  steps:
    - name: Push to another repository
      run: |
        echo "> Starting - Push to another repository script"
        echo "> Git version"
        git --version
        echo "> Completed - Push to another repository script"
