name: Push to another repo example
on:
  push:

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          pwd
          ls -ltr
      - name: Push to another repository
        uses: ./push-to-another-repo/
