name: Push to another repo example
on:
  push:

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push to another repository
        uses: gadaniyati/actions/push-to-another-repo@main
        with:
          source: build-dist
          destination_repo_name: destine-u/test-private
          destination_branch: changes-from-another
          access_key: ${{ secrets.API_TOKEN_GITHUB }}
