name: Push to another repo example
on:
  push:

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push to another repository
        uses: gadaniyati/my-actions/push-to-another-repo@main
        env:
          API_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
