name: Push to another repo example
on:
  push:

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push to another repository
        uses: gadaniyati/my-actions/pust-to-another-repo
